name: Publish Docker image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push image
        id: build-image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha,scope=image
          cache-to: type=gha,mode=max,scope=image
